grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  ingress:
    enabled: true
    ingressClassName: monitoring-nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
    - grafana.local
    path: /
    pathType: Prefix
