- name: "Step 5.0: Check if swap is enabled"
  ansible.builtin.command: swapon --show --noheadings
  register: swap_status
  changed_when: false
  failed_when: false

- name: "Step 5.1: Disable swap (runtime)"
  ansible.builtin.shell: swapoff -a
  when: swap_status.stdout != ""

- name: "Step 5.2: Remove swap entry from /etc/fstab (persist on reboot)"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    state: absent