- name: Deploy Prometheus and Grafana Stack
  hosts: all
  tasks:
    - name: Add Prometheus Helm repo
      ansible.builtin.command:
        cmd: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      become: false

    - name: Update Helm repos
      ansible.builtin.command:
        cmd: helm repo update
      become: false

    - name: Copy grafana-values.yaml to VM
      ansible.builtin.copy:
        src: grafana/grafana-values.yaml
        dest: /home/vagrant/grafana-values.yaml
        owner: vagrant
        group: vagrant
        mode: "0644"


    - name: Install kube-prometheus-stack with values
      kubernetes.core.helm:
        name: monitoring
        chart_ref: kube-prometheus-stack
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        release_namespace: monitoring
        create_namespace: true
        values_files:
          - "/home/vagrant/grafana-values.yaml"
      become: false


    - name: Copy dashboard config to VM
      ansible.builtin.copy:
        src: grafana/dashboard-configmap.yaml
        dest: /home/vagrant/dashboard-configmap.yaml
        owner: vagrant
        group: vagrant
        mode: "0644"
      become: false


    - name: Apply Grafana dashboard ConfigMap
      ansible.builtin.command:
        cmd: kubectl apply -f /home/vagrant/dashboard-configmap.yaml -n monitoring
      become: false
