---
- hosts: workers
  become: true
  strategy: free
  tasks:
    # Step 18
    - name: Check if node is already part of a cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf_stat

    - name: Print command to join the cluster
      ansible.builtin.shell:
        cmd: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      run_once: true
      # changed_when: false
      when: not kubelet_conf_stat.stat.exists

    # Step 19
    - name: Join the cluster
      ansible.builtin.shell:
        cmd: "{{ join_command.stdout }}"
      when: not kubelet_conf_stat.stat.exists
