---
- name: Setup Kubernetes Controller
  hosts: ctrl
  become: true

  tasks:
    #13. init cluster
    - name: Initialize Kubernetes cluster
      ansible.builtin.shell: |
        if [ ! -f /etc/kubernetes/admin.conf ]; then
          kubeadm init --apiserver-advertise-address=192.168.56.100 --node-name ctrl --pod-network-cidr=10.244.0.0/16
        else
          echo "Kubernetes already initialized"
        fi
      become: true

    #14. setup kubectl
    - name: Copy admin kubeconfig to vagrant user
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        mode: '0644'
      become: true

    - name: Set correct permissions on kubeconfig file
      ansible.builtin.file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: '0644'
      become: true

    - name: Copy kubeconfig to host machine
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ playbook_dir }}/kubeconfig"
        mode: '0644'
      delegate_to: localhost

    #15. create Pod network
    - name: Install Flannel Pod Network
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        kubectl set args daemonset kube-flannel-ds -n kube-system --overwrite --add="--iface=eth1"
      become: true

    #16. install Helm
    - name: Add Helm repository GPG key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Helm APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install Helm
      ansible.builtin.apt:
        name: helm
        state: present

- name: Install MetalLB
  hosts: ctrl
  become: true
  tasks:
    #20. apply metalLB config and wait for controller
    - name: Apply MetalLB CRDs and configurations
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/manifests/metallb-native-0.14.9.yaml
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/manifests/ip-address-pool.yaml
        kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/manifests/l2advertisement.yaml
      become: true

    - name: Wait for MetalLB controller to be ready
      ansible.builtin.shell: |
        kubectl wait -n metallb-system -l app=metallb,component=controller --for=condition=ready pod --timeout=60s
      become: true

- name: Install Nginx Ingress Controller
  hosts: ctrl
  become: true
  tasks:
    - name: Add Nginx Ingress Helm repository
      ansible.builtin.shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
      become: true

    - name: Install Nginx Ingress Controller
      ansible.builtin.helm:
        name: ingress-nginx
        chart: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          controller.service.loadBalancerIP: "192.168.56.90"  # Replace with a suitable IP address
      become: true

- name: Install Nginx Ingress Controller
  hosts: ctrl
  become: true
  tasks:
    #21. add nginx ingress and install controller
    - name: Add Nginx Ingress Helm repository
      ansible.builtin.shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
      become: true

    - name: Install Nginx Ingress Controller
      ansible.builtin.helm:
        name: ingress-nginx
        chart: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          controller.service.loadBalancerIP: "192.168.56.90"  # Replace with a suitable IP address
      become: true



  
