---
- hosts: all
  become: true
  vars:
    metallb_version: "v0.14.9"
  tasks:
    # Install MetalLB for LoadBalancer services
    - name: Download MetalLB manifest from GitHub
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
        dest: /home/vagrant/metallb-native.yaml
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Check if MetalLB is already deployed
      ansible.builtin.command:
        cmd: kubectl get namespace metallb-system
      register: metallb_check
      ignore_errors: true
      changed_when: false
      become: false
      become_user: vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config

    - name: Apply MetalLB manifest
      ansible.builtin.command:
        cmd: kubectl apply -f /home/vagrant/metallb-native.yaml
      when: metallb_check.rc != 0
      become: false
      become_user: vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
    
    - name: Wait for MetalLB pods to be ready
      ansible.builtin.command:
        cmd: kubectl -n metallb-system wait -l app=metallb,component=controller --for=condition=Ready pods --all --timeout=60s
      become: false
      become_user: vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: metallb_pods_ready
      changed_when: false
      when: metallb_check.rc != 0
      ignore_errors: true
      retries: 3
      delay: 10


    - name: Create MetalLB configuration
      ansible.builtin.copy:
        dest: /home/vagrant/metallb-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
            - 192.168.56.90-192.168.56.99
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: default
            namespace: metallb-system
          spec:
            ipAddressPools:
            - default-pool
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Apply MetalLB configuration
      ansible.builtin.command:
        cmd: kubectl apply -f /home/vagrant/metallb-config.yaml
      become: false
      become_user: vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
