---
- hosts: all
  become_user: vagrant
  vars:
    metallb_version: "v0.14.9"
  environment:
    KUBECONFIG: /home/vagrant/.kube/config
  tasks:
    # Step 20
    - name: Download MetalLB manifest from GitHub
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
        dest: /home/vagrant/metallb-native.yaml
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Check if MetalLB is already deployed
      ansible.builtin.command:
        cmd: kubectl get namespace metallb-system
      register: metallb_check
      ignore_errors: true
      changed_when: false
      become: false

    - name: Apply MetalLB manifest
      ansible.builtin.command:
        cmd: kubectl apply -f /home/vagrant/metallb-native.yaml
      when: metallb_check.rc != 0
      become: false
    
    - name: Wait for MetalLB pods to be ready
      ansible.builtin.command:
        cmd: kubectl -n metallb-system wait -l app=metallb,component=controller --for=condition=Ready pods --all --timeout=60s
      become: false
      register: metallb_pods_ready
      changed_when: false
      when: metallb_check.rc != 0
      ignore_errors: true
      retries: 3
      delay: 10


    - name: Create MetalLB configuration
      ansible.builtin.copy:
        dest: /home/vagrant/metallb-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
            - 192.168.56.90-192.168.56.99
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: default
            namespace: metallb-system
          spec:
            ipAddressPools:
            - default-pool
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Apply MetalLB configuration
      ansible.builtin.command:
        cmd: kubectl apply -f /home/vagrant/metallb-config.yaml
      become: false

    # Step 21
    - name: Install ingress-nginx with helm
      kubernetes.core.helm:
        # Note: Add ingressClassName:"nginx" to the spec of any Ingress that should use this new IngressController.
        name: ingress-nginx
        chart_ref: ingress-nginx
        chart_repo_url: https://kubernetes.github.io/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          controller:
            service:
              loadBalancerIP: 192.168.56.90
      become: false

    # Step 22
    - name: Install Kubernetes Dashboard with helm
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard
        chart_repo_url: https://kubernetes.github.io/dashboard/
        release_namespace: kubernetes-dashboard
        create_namespace: true
      become: false

    - name: Copy dashboard.yml to host
      become: false
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../k8s/dashboard.yml"
        dest: /home/vagrant/.kube/dashboard.yml
        owner: vagrant
        group: vagrant
        mode: '0644'
          
    - name: Apply dashboard.yml to set up admin user
      become: false
      ansible.builtin.command:
        cmd: kubectl apply -f /home/vagrant/.kube/dashboard.yml
